# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e28030acd729b54fd01ccd688625bb9739f795ad987d17319aea98e22d82b896204b5ad48fb94aa463354c76bc811b78c96959a96521e512b8c4741fae4b4c8

test:
  secret_key_base: 95da0d4469aabb0520e788304b449ab7a55baba691c9cfd240f955ec3e3f35164c8d418efddadd24588ceb7cc622e6a2ecb85c7f597de3f65797e055e21c4a90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
